export const users = [
  { id: 'a1f7k2m-3b9x-41cd', username: 'Alex', email: 'alex@gmail.com' },
  { id: 'b8q4n6p-7d2y-52ef', username: 'Maria', email: 'maria@gmail.com' },
  { id: 'c3w9r1t-5e8z-63fg', username: 'John', email: 'john@gmail.com' },
  { id: 'd6u2i8o-4p7a-74gh', username: 'Emma', email: 'emma@gmail.com' },
  { id: 'e9s5v3k-8l1m-85hi', username: 'Michael', email: 'michael@gmail.com' },
  { id: 'f4x7c2n-6q9w-96ij', username: 'Sophie', email: 'sophie@gmail.com' },
  { id: 'g1z8b5r-3t6y-17jk', username: 'Daniel', email: 'daniel@gmail.com' },
  { id: 'h7m4p9v-2k5x-28kl', username: 'Olivia', email: 'olivia@gmail.com' },
  { id: 'i2n6q8s-9w3e-39lm', username: 'James', email: 'james@gmail.com' },
  { id: 'j5r1t7y-4u8i-41mn', username: 'Anna', email: 'anna@gmail.com' },
  { id: 'k9c3v6x-1z5b-52no', username: 'David', email: 'david@gmail.com' },
  { id: 'l4p8s2w-7n3m-63op', username: 'Laura', email: 'laura@gmail.com' },
  { id: 'm7q1e5r-9t4y-74pq', username: 'Robert', email: 'robert@gmail.com' },
  { id: 'n3w6u8i-2o5p-85qr', username: 'Kate', email: 'kate@gmail.com' },
  { id: 'o8a4d1f-6g9h-96rs', username: 'Thomas', email: 'thomas@gmail.com' },
  { id: 'p2k7m5v-3x8z-17st', username: 'Julia', email: 'julia@gmail.com' },
  { id: 'q6n9b2c-5d1e-28tu', username: 'Chris', email: 'chris@gmail.com' },
  { id: 'r1v4s8w-7y3u-39uv', username: 'Nina', email: 'nina@gmail.com' },
  { id: 's5x2z7k-9m4p-41vw', username: 'Andrew', email: 'andrew@gmail.com' },
  { id: 't8c6q1n-3r5y-52xy', username: 'Elena', email: 'elena@gmail.com' },
];