export const users = [
  { id: 'a1f7k2m-3b9x-41cd', name: 'Alex', email: 'alex@gmail.com' },
  { id: 'b8q4n6p-7d2y-52ef', name: 'Maria', email: 'maria@gmail.com' },
  { id: 'c3w9r1t-5e8z-63fg', name: 'John', email: 'john@gmail.com' },
  { id: 'd6u2i8o-4p7a-74gh', name: 'Emma', email: 'emma@gmail.com' },
  { id: 'e9s5v3k-8l1m-85hi', name: 'Michael', email: 'michael@gmail.com' },
  { id: 'f4x7c2n-6q9w-96ij', name: 'Sophie', email: 'sophie@gmail.com' },
  { id: 'g1z8b5r-3t6y-17jk', name: 'Daniel', email: 'daniel@gmail.com' },
  { id: 'h7m4p9v-2k5x-28kl', name: 'Olivia', email: 'olivia@gmail.com' },
  { id: 'i2n6q8s-9w3e-39lm', name: 'James', email: 'james@gmail.com' },
  { id: 'j5r1t7y-4u8i-41mn', name: 'Anna', email: 'anna@gmail.com' },
  { id: 'k9c3v6x-1z5b-52no', name: 'David', email: 'david@gmail.com' },
  { id: 'l4p8s2w-7n3m-63op', name: 'Laura', email: 'laura@gmail.com' },
  { id: 'm7q1e5r-9t4y-74pq', name: 'Robert', email: 'robert@gmail.com' },
  { id: 'n3w6u8i-2o5p-85qr', name: 'Kate', email: 'kate@gmail.com' },
  { id: 'o8a4d1f-6g9h-96rs', name: 'Thomas', email: 'thomas@gmail.com' },
  { id: 'p2k7m5v-3x8z-17st', name: 'Julia', email: 'julia@gmail.com' },
  { id: 'q6n9b2c-5d1e-28tu', name: 'Chris', email: 'chris@gmail.com' },
  { id: 'r1v4s8w-7y3u-39uv', name: 'Nina', email: 'nina@gmail.com' },
  { id: 's5x2z7k-9m4p-41vw', name: 'Andrew', email: 'andrew@gmail.com' },
  { id: 't8c6q1n-3r5y-52xy', name: 'Elena', email: 'elena@gmail.com' },
];